#!/bin/env bash

last_release=$(git for-each-ref --sort=-creatordate --format='%(refname:short)' "refs/tags/v*" | head -n 1)
commits=$(git log $last_release..master --pretty=format:"%s" --reverse)
commits_doubleslash=$(echo -n "$commits" | awk '{printf "%s\\n", $0}')

prompt="请严格按以下规则处理 Git 提交记录：

■ 绝对禁令
1. 禁止任何自然语言回复
2. 禁止使用"好的""以下是"等引导语
3. 禁止添加标题以外的任何解释性文本
4. 禁止添加任何说明
5. 禁止把输出放进Markdown代码块中
6. 严禁添加 [English] 和 [中文] 等语言标签

■ 输出格式
### 📖 摘要 Summary
[无任何前缀的英文摘要]
[对应中文摘要]

### 🚀 新功能 Features
- 模块前缀: 中文描述
  英文描述 (必须换行且缩进对齐)
  
### 🐞 修复 Bug Fixes
- 修复中文描述 
  英文描述 (必须换行且缩进对齐)

■ 执行规范 (违规将导致格式错误)
1. 以###标题为起始，无空行前缀
2. 摘要部分直接显示内容，删除[ ]标签
3. 功能/修复条目必须严格使用两级缩进：
   - 首行：中文 (带模块前缀)
   - 次行：英文 (首字母大写，无句号)
4. 全文档禁用以下词汇：
   └─ 用户提供/整理如下/Changelog/根据记录/以下内容

■ 处理流程
1. 过滤无效提交 → 2. 语义聚类 → 3. 生成摘要 → 4. 格式化输出"
prompt_doubleslash=$(echo -n "$prompt" | awk '{printf "%s\\n", $0}')

response=$(curl "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-lite:generateContent?key=$GEMINI_API_KEY" \
  -s \
  -H 'Content-Type: application/json' \
  -X POST \
  -d "{
    \"contents\": [
      {
        \"role\": \"user\",
        \"parts\": [{
          \"text\": \"$prompt_doubleslash\"
        }]
      },
      {
        \"role\": \"model\",
        \"parts\": [{
          \"text\": \"好的！请提供 Git 提交历史记录，我会帮你整理成结构化的 Changelog。\"
        }]
      },
      {
        \"role\": \"user\",
        \"parts\": [{
          \"text\": \"$commits_doubleslash\"
        }]
      }
    ],
    \"generationConfig\": {
      \"temperature\": 1.1,
      \"maxOutputTokens\": 1000,
      \"topP\": 1.0,
      \"topK\": 1
    }
  }")

# echo "$response"

changelog=$(echo "$response" |
  jq -r '.candidates[0].content.parts[0].text' |
  sed -n '/### 📖/,$p' |
  sed 's/```//g')
changelog="$changelog

---

###### Time range / 时间范围: $last_release..master
###### [View full changelog / 查看完整更新日志](https://github.com/LiRenTech/project-graph/compare/$last_release...master)
###### Generated by Google Gemini / 由 Google Gemini 生成
"

echo "$changelog"
