#!/bin/env bash

commits=$(git log nightly..master --pretty=format:"%an %s" --reverse)
commits_doubleslash=$(echo -n "$commits" | awk '{printf "%s\\n", $0}')

prompt="请严格按以下规则处理 Git 提交记录：

■ 绝对禁令
1. 禁止任何自然语言回复
2. 禁止使用"好的""以下是"等引导语
3. 禁止添加标题以外的任何解释性文本
4. 禁止添加任何说明
5. 禁止把输出放进Markdown代码块中
6. 严禁添加 [English] 和 [中文] 等语言标签

■ 输出格式
### 📖 摘要 Summary
[无任何前缀的英文摘要]
[对应中文摘要]

### 🚀 新功能 Features
- 模块前缀: 中文描述
  英文描述 (必须换行且缩进对齐)
  
### 🐞 修复 Bug Fixes
- 修复中文描述 
  英文描述 (必须换行且缩进对齐)

■ 执行规范 (违规将导致格式错误)
1. 以###标题为起始，无空行前缀
2. 摘要部分直接显示内容，删除[ ]标签
3. 功能/修复条目必须严格使用两级缩进：
   - 首行：中文 (带模块前缀)
   - 次行：英文 (首字母大写，无句号)
4. 全文档禁用以下词汇：
   └─ 用户提供/整理如下/Changelog/根据记录/以下内容

■ 处理流程
1. 过滤无效提交 → 2. 语义聚类 → 3. 生成摘要 → 4. 格式化输出"
prompt_doubleslash=$(echo -n "$prompt" | awk '{printf "%s\\n", $0}')

changelog=$(curl "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-lite:generateContent?key=$GEMINI_API_KEY" \
  -s \
  -H 'Content-Type: application/json' \
  -X POST \
  -d "{
    \"contents\": [
      {
        \"role\": \"user\",
        \"parts\": [{
          \"text\": \"请将用户提供的 Git 提交历史记录按以下结构化格式整理：\n\n### 📖 Summary 摘要\n[英文版] \n用1-2句简明英文概括本次更新的核心内容，突出主要改进方向\n\n[中文版]\n用流畅自然的中文复述英文摘要，保持专业技术文档语气\n\n### 🚀 Features 新功能\n- 使用小标题+冒号格式提取功能项 (例: Auth: 新增第三方登录支持)\n- 每条功能描述需中英双语对照\n- 优先展示影响较大的功能\n- 相同模块的功能合并展示\n\n### 🐞 Bug Fixes 修复\n- 用\\"修复XX问题\\"作为标准开头\n- 包含问题现象和影响范围说明 (例: 修复内存泄漏导致服务崩溃的问题)\n- 技术细节使用中文描述\n- 按问题严重性排序\n\n处理要求：\n1. 自动过滤Merge branch/update version等无意义提交\n2. 对相似提交进行智能合并\n3. 中英文内容需保持严格对应\n4. 使用技术术语保持准确\n5. 输出使用GitHub风格的Markdown格式\"
        }]
      },
      {
        \"role\": \"model\",
        \"parts\": [{
          \"text\": \"好的！请提供 Git 提交历史记录，我会帮你整理成结构化的 Changelog。\"
        }]
      },
      {
        \"role\": \"user\",
        \"parts\": [{
          \"text\": \"$commits_doubleslash\"
        }]
      }
    ],
    \"generationConfig\": {
      \"temperature\": 1.1,
      \"maxOutputTokens\": 1000,
      \"topP\": 1.0,
      \"topK\": 1
    }
  }" |
  jq -r '.candidates[0].content.parts[0].text' |
  sed -n '/### 📖/,$p')

changelog="$changelog

---

###### [View full changelog / 查看完整更新日志](https://github.com/LiRenTech/project-graph/compare/nightly...master)
###### Generated by Google Gemini / 由 Google Gemini 生成
"

echo "$changelog"
