import {
  AlignStartVertical,
  AppWindow,
  AppWindowMac,
  ArrowDownNarrowWide,
  ArrowUpRight,
  Blend,
  Bot,
  Box,
  Brain,
  Bug,
  Calculator,
  Camera,
  CaseSensitive,
  Clock,
  Columns4,
  Cpu,
  Crosshair,
  Database,
  Eye,
  FileStack,
  Folder,
  Fullscreen,
  Gamepad,
  Grab,
  Grip,
  Hand,
  HandMetal,
  HardDrive,
  HardDriveDownload,
  Hourglass,
  ImageMinus,
  ImageUpscale,
  Keyboard,
  Languages,
  Layers,
  ListCheck,
  ListCollapse,
  ListEnd,
  ListRestart,
  ListTree,
  MemoryStick,
  Mouse,
  MousePointerClick,
  Move,
  Move3d,
  MoveHorizontal,
  MoveVertical,
  Network,
  PictureInPicture,
  Presentation,
  Ratio,
  ReceiptText,
  RefreshCcwDot,
  RotateCw,
  Rows4,
  Save,
  Scaling,
  ScanEye,
  ScanText,
  Skull,
  Space,
  Sparkle,
  Spline,
  Square,
  SquareArrowDownRight,
  SquareArrowUpLeft,
  SquareDashedMousePointer,
  SquareM,
  Tag,
  Text,
  TextCursorInput,
  TextSelect,
  Touchpad,
  Turtle,
  Undo,
  Ungroup,
  VenetianMask,
  Workflow,
  Wrench,
  Zap,
  ZoomIn,
} from "lucide-react";

export const settingsCategoriesIcons = {
  ai: {
    icon: Brain,
    api: Network,
  },
  automation: {
    icon: Bot,
    autoNamer: Text,
    autoSave: Save,
    autoBackup: Folder,
  },
  control: {
    icon: Wrench,
    mouse: Mouse,
    touchpad: Touchpad,
    cameraMove: Camera,
    cameraZoom: ZoomIn,
    rectangleSelect: SquareDashedMousePointer,
    textNode: TextSelect,
    edge: ArrowUpRight,
    generateNode: Network,
    gamepad: Gamepad,
  },
  performance: {
    icon: Zap,
    memory: MemoryStick,
    cpu: Cpu,
    render: Clock,
    experimental: Sparkle,
  },
  visual: {
    icon: Eye,
    basic: AppWindowMac,
    background: Layers,
    node: Workflow,
    edge: ArrowUpRight,
    section: Box,
    entityDetails: ReceiptText,
    debug: Bug,
    miniWindow: PictureInPicture,
    experimental: Sparkle,
  },
};

export const settingsIcons = {
  autoNamerTemplate: Tag,
  autoNamerSectionTemplate: Tag,
  autoSaveWhenClose: HardDriveDownload,
  autoSave: HardDrive,
  autoSaveInterval: Hourglass,
  autoBackup: Database,
  autoBackupInterval: Hourglass,
  autoBackupLimitCount: FileStack,
  autoBackupDraftPath: Folder,
  mouseRightDragBackground: MousePointerClick,
  enableDragAutoAlign: AlignStartVertical,
  mouseWheelMode: Mouse,
  mouseWheelWithShiftMode: Mouse,
  mouseWheelWithCtrlMode: Mouse,
  mouseWheelWithAltMode: Mouse,
  doubleClickMiddleMouseButton: Mouse,
  mouseSideWheelMode: Grab,
  macMouseWheelIsSmoothed: Mouse,
  enableWindowsTouchPad: Hand,
  macTrackpadAndMouseWheelDifference: Hand,
  macTrackpadScaleSensitivity: HandMetal,
  allowMoveCameraByWSAD: Keyboard,
  cameraFollowsSelectedNodeOnArrowKeys: Crosshair,
  cameraKeyboardMoveReverse: Keyboard,
  moveAmplitude: Move,
  moveFriction: Move,
  scaleExponent: ScanEye,
  cameraResetViewPaddingRate: Fullscreen,
  scaleCameraByMouseLocation: ScanEye,
  cameraKeyboardScaleRate: ScanEye,
  rectangleSelectWhenRight: SquareArrowDownRight,
  rectangleSelectWhenLeft: SquareArrowUpLeft,
  textNodeStartEditMode: ListRestart,
  textNodeContentLineBreak: ListEnd,
  textNodeExitEditMode: ListCheck,
  textNodeSelectAllWhenStartEditByMouseClick: TextCursorInput,
  textNodeSelectAllWhenStartEditByKeyboard: TextCursorInput,
  allowAddCycleEdge: RotateCw,
  autoLayoutWhenTreeGenerate: ListTree,
  gamepadDeadzone: Skull,
  historySize: Undo,
  compressPastedImages: ImageMinus,
  maxPastedImageSize: ImageUpscale,
  autoRefreshStageByMouseAction: RefreshCcwDot,
  isPauseRenderWhenManipulateOvertime: Hourglass,
  renderOverTimeWhenNoManipulateTime: Hourglass,
  ignoreTextNodeTextRenderLessThanCameraScale: ScanText,
  textCacheSize: MemoryStick,
  textScalingBehavior: Text,
  antialiasing: Calculator,
  compatibilityMode: Turtle,
  isEnableEntityCollision: Ungroup,
  language: Languages,
  showTipsOnUI: AppWindow,
  useNativeTitleBar: AppWindowMac,
  isClassroomMode: Presentation,
  windowBackgroundAlpha: Blend,
  isRenderCenterPointer: Crosshair,
  showBackgroundHorizontalLines: Rows4,
  showBackgroundVerticalLines: Columns4,
  showBackgroundDots: Grip,
  showBackgroundCartesian: Move3d,
  enableTagTextNodesBigDisplay: Tag,
  showTextNodeBorder: Square,
  lineStyle: Spline,
  sectionBitTitleRenderType: SquareM,
  nodeDetailsPanel: AppWindow,
  alwaysShowDetails: ListCollapse,
  entityDetailsFontSize: CaseSensitive,
  entityDetailsLinesLimit: ArrowDownNarrowWide,
  entityDetailsWidthLimit: Space,
  showDebug: Bug,
  protectingPrivacy: VenetianMask,
  windowCollapsingWidth: MoveHorizontal,
  windowCollapsingHeight: MoveVertical,
  limitCameraInCycleSpace: Ratio,
  cameraCycleSpaceSizeX: Scaling,
  cameraCycleSpaceSizeY: Scaling,
};
