import { glob, writeFile } from "node:fs/promises";
import { createLogger, Plugin } from "vite";
import { convertThemeToCss, generateUtilities, parseThemeFiles } from "./theme";

const logger = createLogger("info", { prefix: "[pg-theme]" });

interface Config {
  /** 主题文件glob */
  glob: string | string[];
  /** 输出文件路径 */
  out: string;
  /** 默认主题id */
  defaultTheme: string;
}

export default function pgTheme(pluginConfig: Config): Plugin {
  return {
    name: "pg-theme",
    async configResolved() {
      await generateAndWrite(pluginConfig);
    },
    async handleHotUpdate(ctx) {
      for await (const file of glob(pluginConfig.glob)) {
        if (ctx.file.endsWith(file)) {
          try {
            await generateAndWrite(pluginConfig);
          } catch (e) {
            logger.error(String(e));
          }
          break;
        }
      }
    },
  };
}

async function generateAndWrite(pluginConfig: Config) {
  logger.info("重新生成主题文件", { timestamp: true });
  const themes = await parseThemeFiles(pluginConfig.glob);
  const defaultTheme = themes.find((theme) => theme.metadata.id === pluginConfig.defaultTheme);
  if (!defaultTheme) {
    logger.error(`未找到默认主题 ${pluginConfig.defaultTheme}`, { timestamp: true });
    return;
  }
  // 生成tailwindcss主题
  const cssVariables = convertThemeToCss(defaultTheme.content);
  const tailwindUtilities = generateUtilities(defaultTheme.content);
  const tailwindTheme = `\
@theme inline {
  ${cssVariables}
}
${tailwindUtilities}
`
    // .replaceAll("\n", "")
    // .replaceAll(" ", "")
    .trim();
  const withComments = `\
/* eslint-disable */
/* prettier-ignore */
/* Generated by vite-plugin-pg-theme */
${tailwindTheme}
`;
  // 写入文件
  await writeFile(pluginConfig.out, withComments, "utf-8");
  logger.info("主题文件生成完成", { timestamp: true });
}
