/**
 * 所有鼠标光标的名称枚举
 */
export enum CursorNameEnum {
  Default = "cursor-default",
  Pointer = "cursor-pointer",
  Crosshair = "cursor-crosshair",
  Move = "cursor-move",
  Grab = "cursor-grab",
  Grabbing = "cursor-grabbing",
  Text = "cursor-text",
  NotAllowed = "cursor-not-allowed",
  EResize = "cursor-e-resize",
  NResize = "cursor-n-resize",
  NeResize = "cursor-ne-resize",
  NwResize = "cursor-nw-resize",
  SResize = "cursor-s-resize",
  SeResize = "cursor-se-resize",
  SwResize = "cursor-sw-resize",
  WResize = "cursor-w-resize",
  NsResize = "cursor-ns-resize",
  NeswResize = "cursor-nesw-resize",
  NwseResize = "cursor-nwse-resize",
  ColResize = "cursor-col-resize",
  RowResize = "cursor-row-resize",
  AllScroll = "cursor-all-scroll",
  ZoomIn = "cursor-zoom-in",
  ZoomOut = "cursor-zoom-out",
  GrabHand = "cursor-grab-hand",
  NotAllowedHand = "cursor-not-allowed-hand",
  Pen = "cursor-pen",
  Eraser = "cursor-eraser",
  Handwriting = "cursor-handwriting",
  ZoomInHand = "cursor-zoom-in-hand",
  ZoomOutHand = "cursor-zoom-out-hand",
}
