export const settingsCategories = {
  ai: {
    api: ["aiApiBaseUrl", "aiApiKey", "aiModel", "aiShowTokenCount"],
  },
  automation: {
    autoNamer: ["autoNamerTemplate", "autoNamerSectionTemplate"],
    autoSave: ["autoSaveWhenClose", "autoSave", "autoSaveInterval"],
    autoBackup: ["autoBackup", "autoBackupInterval", "autoBackupLimitCount", "autoBackupDraftPath"],
  },
  control: {
    mouse: [
      "mouseRightDragBackground",
      "enableDragAutoAlign",
      "mouseWheelMode",
      "mouseWheelWithShiftMode",
      "mouseWheelWithCtrlMode",
      "mouseWheelWithAltMode",
      "doubleClickMiddleMouseButton",
      "mouseSideWheelMode",
      "macMouseWheelIsSmoothed",
    ],
    touchpad: ["enableWindowsTouchPad", "macTrackpadAndMouseWheelDifference", "macTrackpadScaleSensitivity"],
    cameraMove: [
      "allowMoveCameraByWSAD",
      "cameraFollowsSelectedNodeOnArrowKeys",
      "cameraKeyboardMoveReverse",
      "moveAmplitude",
      "moveFriction",
    ],
    cameraZoom: [
      "scaleExponent",
      "cameraResetViewPaddingRate",
      "scaleCameraByMouseLocation",
      "cameraKeyboardScaleRate",
    ],
    rectangleSelect: ["rectangleSelectWhenRight", "rectangleSelectWhenLeft"],
    textNode: [
      "textNodeStartEditMode",
      "textNodeContentLineBreak",
      "textNodeExitEditMode",
      "textNodeSelectAllWhenStartEditByMouseClick",
      "textNodeSelectAllWhenStartEditByKeyboard",
    ],
    edge: ["allowAddCycleEdge"],
    generateNode: ["autoLayoutWhenTreeGenerate"],
    gamepad: ["gamepadDeadzone"],
  },
  performance: {
    memory: ["historySize"],
    cpu: ["autoRefreshStageByMouseAction"],
    render: [
      "isPauseRenderWhenManipulateOvertime",
      "renderOverTimeWhenNoManipulateTime",
      "scaleExponent",
      "ignoreTextNodeTextRenderLessThanCameraScale",
      "textCacheSize",
      "textScalingBehavior",
      "antialiasing",
    ],
    experimental: ["compatibilityMode", "isEnableEntityCollision"],
  },
  visual: {
    basic: ["language", "showTipsOnUI", "useNativeTitleBar", "isClassroomMode", "windowBackgroundAlpha"],
    background: [
      "isRenderCenterPointer",
      "showBackgroundHorizontalLines",
      "showBackgroundVerticalLines",
      "showBackgroundDots",
      "showBackgroundCartesian",
    ],
    node: ["enableTagTextNodesBigDisplay", "showTextNodeBorder"],
    edge: ["lineStyle"],
    section: ["sectionBitTitleRenderType"],
    entityDetails: [
      "nodeDetailsPanel",
      "alwaysShowDetails",
      "entityDetailsFontSize",
      "entityDetailsLinesLimit",
      "entityDetailsWidthLimit",
    ],
    debug: ["showDebug", "protectingPrivacy"],
    miniWindow: ["windowCollapsingWidth", "windowCollapsingHeight"],
    experimental: ["limitCameraInCycleSpace", "cameraCycleSpaceSizeX", "cameraCycleSpaceSizeY"],
  },
};
