import { Project } from "./Project";
import { CurveRenderer } from "./render/canvas2d/basicRenderer/curveRenderer";
import { ImageRenderer } from "./render/canvas2d/basicRenderer/ImageRenderer";
import { ShapeRenderer } from "./render/canvas2d/basicRenderer/shapeRenderer";
import { SvgRenderer } from "./render/canvas2d/basicRenderer/svgRenderer";
import { TextRenderer } from "./render/canvas2d/basicRenderer/textRenderer";
import { DrawingControllerRenderer } from "./render/canvas2d/controllerRenderer/drawingRenderer";
import { CollisionBoxRenderer } from "./render/canvas2d/entityRenderer/CollisionBoxRenderer";
import { StraightEdgeRenderer } from "./render/canvas2d/entityRenderer/edge/concrete/StraightEdgeRenderer";
import { SymmetryCurveEdgeRenderer } from "./render/canvas2d/entityRenderer/edge/concrete/SymmetryCurveEdgeRenderer";
import { VerticalPolyEdgeRenderer } from "./render/canvas2d/entityRenderer/edge/concrete/VerticalPolyEdgeRenderer";
import { EdgeRenderer } from "./render/canvas2d/entityRenderer/edge/EdgeRenderer";
import { EntityDetailsButtonRenderer } from "./render/canvas2d/entityRenderer/EntityDetailsButtonRenderer";
import { EntityRenderer } from "./render/canvas2d/entityRenderer/EntityRenderer";
import { MultiTargetUndirectedEdgeRenderer } from "./render/canvas2d/entityRenderer/multiTargetUndirectedEdge/MultiTargetUndirectedEdgeRenderer";
import { PortalNodeRenderer } from "./render/canvas2d/entityRenderer/portalNode/portalNodeRenderer";
import { SectionRenderer } from "./render/canvas2d/entityRenderer/section/SectionRenderer";
import { SvgNodeRenderer } from "./render/canvas2d/entityRenderer/svgNode/SvgNodeRenderer";
import { TextNodeRenderer } from "./render/canvas2d/entityRenderer/textNode/TextNodeRenderer";
import { UrlNodeRenderer } from "./render/canvas2d/entityRenderer/urlNode/urlNodeRenderer";
import { Renderer } from "./render/canvas2d/renderer";
import { BackgroundRenderer } from "./render/canvas2d/utilsRenderer/backgroundRenderer";
import { RenderUtils } from "./render/canvas2d/utilsRenderer/RenderUtils";
import { SearchContentHighlightRenderer } from "./render/canvas2d/utilsRenderer/searchContentHighlightRenderer";
import { WorldRenderUtils } from "./render/canvas2d/utilsRenderer/WorldRenderUtils";
import { InputElement } from "./render/domElement/inputElement";
import { AutoLayoutFastTree } from "./service/controlService/autoLayoutEngine/autoLayoutFastTreeMode";
import { AutoLayout } from "./service/controlService/autoLayoutEngine/mainTick";
import { ControllerUtils } from "./service/controlService/controller/concrete/utilsControl";
import { Controller } from "./service/controlService/controller/Controller";
import { KeyboardOnlyEngine } from "./service/controlService/keyboardOnlyEngine/keyboardOnlyEngine";
import { KeyboardOnlyGraphEngine } from "./service/controlService/keyboardOnlyEngine/keyboardOnlyGraphEngine";
import { KeyboardOnlyTreeEngine } from "./service/controlService/keyboardOnlyEngine/keyboardOnlyTreeEngine";
import { SelectChangeEngine } from "./service/controlService/keyboardOnlyEngine/selectChangeEngine";
import { RectangleSelect } from "./service/controlService/rectangleSelectEngine/rectangleSelectEngine";
import { SecretKeys } from "./service/controlService/secretKeysEngine/secretKeysEngine";
import { KeyBinds } from "./service/controlService/shortcutKeysEngine/KeyBinds";
import { KeyBindsRegistrar } from "./service/controlService/shortcutKeysEngine/shortcutKeysRegister";
import { MouseInteraction } from "./service/controlService/stageMouseInteractionCore/stageMouseInteractionCore";
import { AutoComputeUtils } from "./service/dataGenerateService/autoComputeEngine/AutoComputeUtils";
import { AutoCompute } from "./service/dataGenerateService/autoComputeEngine/mainTick";
import { GenerateFromFolder } from "./service/dataGenerateService/generateFromFolderEngine/GenerateFromFolderEngine";
import { StageExport } from "./service/dataGenerateService/stageExportEngine/stageExportEngine";
import { StageExportPng } from "./service/dataGenerateService/stageExportEngine/StageExportPng";
import { StageExportSvg } from "./service/dataGenerateService/stageExportEngine/StageExportSvg";
import { AIEngine } from "./service/dataManageService/aiEngine/AIEngine";
import { ComplexityDetector } from "./service/dataManageService/ComplexityDetector";
import { ContentSearch } from "./service/dataManageService/contentSearchEngine/contentSearchEngine";
import { CopyEngine } from "./service/dataManageService/copyEngine/copyEngine";
import { Effects } from "./service/feedbackService/effectEngine/effectMachine";
import { StageStyleManager } from "./service/feedbackService/stageStyle/StageStyleManager";
import { Camera } from "./stage/Camera";
import { Canvas } from "./stage/Canvas";
import { StageDumper } from "./stage/StageDumper";
import { SectionMethods } from "./stage/stageManager/basicMethods/SectionMethods";
import { LayoutManualAlign } from "./stage/stageManager/concreteMethods/layoutManager/layoutManualAlignManager";
import { AutoAlign } from "./stage/stageManager/concreteMethods/StageAutoAlignManager";
import { DeleteManager } from "./stage/stageManager/concreteMethods/StageDeleteManager";
import { EntityMoveManager } from "./stage/stageManager/concreteMethods/StageEntityMoveManager";
import { StageUtils } from "./stage/stageManager/concreteMethods/StageManagerUtils";
import { MultiTargetEdgeMove } from "./stage/stageManager/concreteMethods/StageMultiTargetEdgeMove";
import { NodeAdder } from "./stage/stageManager/concreteMethods/StageNodeAdder";
import { NodeConnector } from "./stage/stageManager/concreteMethods/StageNodeConnector";
import { StageNodeRotate } from "./stage/stageManager/concreteMethods/stageNodeRotate";
import { StageObjectColorManager } from "./stage/stageManager/concreteMethods/StageObjectColorManager";
import { StageObjectSelectCounter } from "./stage/stageManager/concreteMethods/StageObjectSelectCounter";
import { SectionInOutManager } from "./stage/stageManager/concreteMethods/StageSectionInOutManager";
import { SectionPackManager } from "./stage/stageManager/concreteMethods/StageSectionPackManager";
import { SerializedDataAdder } from "./stage/stageManager/concreteMethods/StageSerializedAdder";
import { TagManager } from "./stage/stageManager/concreteMethods/StageTagManager";
import { HistoryManager } from "./stage/stageManager/StageHistoryManager";
import { StageManager } from "./stage/stageManager/StageManager";

export function loadAllServices(project: Project): void {
  project.loadService(Canvas);
  project.loadService(InputElement);
  project.loadService(StageStyleManager);
  project.loadService(KeyBinds);
  project.loadService(ControllerUtils);
  project.loadService(SectionMethods);
  project.loadService(Controller);
  project.loadService(AutoComputeUtils);
  project.loadService(RenderUtils);
  project.loadService(WorldRenderUtils);
  project.loadService(StageManager);
  project.loadService(Camera);
  project.loadService(Effects);
  project.loadService(AutoCompute);
  project.loadService(SecretKeys);
  project.loadService(StageDumper);
  project.loadService(HistoryManager);
  project.loadService(RectangleSelect);
  project.loadService(StageNodeRotate);
  project.loadService(ComplexityDetector);
  project.loadService(AIEngine);
  project.loadService(CopyEngine);
  project.loadService(AutoLayout);
  project.loadService(AutoLayoutFastTree);
  project.loadService(LayoutManualAlign);
  project.loadService(AutoAlign);
  project.loadService(MouseInteraction);
  project.loadService(ContentSearch);
  project.loadService(DeleteManager);
  project.loadService(NodeAdder);
  project.loadService(EntityMoveManager);
  project.loadService(StageUtils);
  project.loadService(MultiTargetEdgeMove);
  project.loadService(NodeConnector);
  project.loadService(StageObjectColorManager);
  project.loadService(StageObjectSelectCounter);
  project.loadService(SectionInOutManager);
  project.loadService(SectionPackManager);
  project.loadService(TagManager);
  project.loadService(KeyboardOnlyEngine);
  project.loadService(KeyboardOnlyGraphEngine);
  project.loadService(KeyboardOnlyTreeEngine);
  project.loadService(SelectChangeEngine);
  project.loadService(TextRenderer);
  project.loadService(ImageRenderer);
  project.loadService(ShapeRenderer);
  project.loadService(EntityRenderer);
  project.loadService(MultiTargetUndirectedEdgeRenderer);
  project.loadService(CurveRenderer);
  project.loadService(SvgRenderer);
  project.loadService(DrawingControllerRenderer);
  project.loadService(CollisionBoxRenderer);
  project.loadService(EntityDetailsButtonRenderer);
  project.loadService(StraightEdgeRenderer);
  project.loadService(SymmetryCurveEdgeRenderer);
  project.loadService(VerticalPolyEdgeRenderer);
  project.loadService(EdgeRenderer);
  project.loadService(PortalNodeRenderer);
  project.loadService(SectionRenderer);
  project.loadService(SvgNodeRenderer);
  project.loadService(TextNodeRenderer);
  project.loadService(UrlNodeRenderer);
  project.loadService(BackgroundRenderer);
  project.loadService(SearchContentHighlightRenderer);
  project.loadService(Renderer);
  project.loadService(StageExport);
  project.loadService(StageExportPng);
  project.loadService(StageExportSvg);
  project.loadService(GenerateFromFolder);
  project.loadService(SerializedDataAdder);
  project.loadService(KeyBindsRegistrar);
}
