name: "Feature Preview"

on:
  push:
    branches:
      - feat/**

jobs:
  delete-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: gh release delete fp-${{ github.ref_name }} --yes --cleanup-tag || true # 忽略错误
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  create-release:
    needs: delete-release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: 'gh release create fp-${{ github.ref_name }} --title "Feature Preview: ${{ github.ref_name }}" --prerelease'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-tauri:
    needs: create-release
    permissions:
      contents: write

    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "./src-tauri -> target"

      - name: edit version
        run: |
          $jsonContent = Get-Content -Path "src-tauri/tauri.conf.json" -Raw
          $jsonObject = $jsonContent | ConvertFrom-Json
          $jsonObject.version = "0.0.0-fp.${{ github.ref_name }}.r${{ github.run_number }}"
          $jsonObject | ConvertTo-Json -Depth 10 | Set-Content -Path "src-tauri/tauri.conf.json"

      - uses: tauri-apps/tauri-action@dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LR_GITHUB_CLIENT_SECRET: ${{ secrets.ENV_GITHUB_CLIENT_SECRET }}
          LR_API_BASE_URL: ${{ secrets.ENV_API_BASE_URL }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          projectPath: "./app"
          # upload to release
          tagName: fp-${{ github.ref_name }}
